### ISSUE TITLE
Return all models related to Trial in the endpoint

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/api#21]
- [x] Persons
- [x] Organisations
- [x] Problems
- [ ] Documents
- [ ] Publications
- [ ] Records

In our DB, a "condition" is a type of "problem". Maybe we should expose them as "conditions", as it's the naming used by (for example) https://clinicaltrials.gov/ct2/show/NCT00112593, and is more neutral.

@roll What other types of problems you thought on adding to the "problems" table?

**Comment by roll** [comment]
@vitorbaptista 
related to https://github.com/opentrials/opentrials/issues/30

Problem could be a `smoking` for example or `bad ecology` - I don't know how we could classify it - just `other`?

Here is a reference - http://www.who.int/ictrp/network/trds/en/

> **Health Condition(s) or Problem(s) Studied**
> Primary health condition(s) or problem(s) studied (e.g., depression, breast cancer, medication error).
> If the study is conducted in healthy human volunteers belonging to the target population of the intervention (e.g. preventive or screening interventions), enter the particular health condition(s) or problem(s) being prevented.

**Comment by pwalsh** [comment]
@vitorbaptista @roll closing this. Adding extra data to endpoints will come out of implementing features, so at this stage, i dont think we need this to capture that.
