### ISSUE TITLE
Initial database schema

### ISSUE THREAD

**Issue by pwalsh** [opentrials/api#3]
# Description

First iteration on the database schema for the OpenTrials API.

This database:

* Holds a normalised representation of data, extracted from the Warehouse
* Is read only
* Powers all endpoints of the OpenTrials API that expose READ data
  * It is expected that as we progress, some WRITE endpoints will be exposed via the API, but that these would write into the Warehouse, as new data would need to be matched/processed into the rest of the data.

### Reference tables

This is data we'll extract out of the trial data and write into normalised tables that our "ideal trial" objects reference. In order to build these tables, we may first push some of the data from a trial through some type of entity reconciliation service, or other in order to build out full objects from the info in the trial. 

The simplest example of this is location data: We can match locations with info from [OKI's Cosmopolitan API](http://cosmopolitan.openspending.org) or similar, and have a properly normalised location table to reference.

Also, while in the first iterations of our database, these reference tables would not be fully de-duped/reconciled, we'd iterate on them over time, as we acquire more data in general. A simple example of this is that we'll start to acquire data from various sources on Interventions, and via de-dupe / record matching, tidy up our Intervention table.

Every trial should have at least one of each of these entities, and there are likely other such entities we can extract into reference tables over time.

* **Location**: A geographical location
  * Cosmopolitan should have most of the data we need here. The primary data source in cosmopolitan is geonames. The structure of this table depends on how detailed the location information is across trials. Likely just city + country?
* **Person**: Persons associated with trial data
  * Belongs to one or many organisations
  * Belongs to one or many trials
  * Belongs to one or many publications
  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
* **Organisation**: Organisations associated with trial data
  * Belongs to one or many trials
  * Has one or many persons
  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
* **Intervention**: Interventions associated with trial data
  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
* **Condition**: Conditions associated with trial data
  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
* **DataSource**: A source of data in the database
  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM) (register, etc.)
    * Most other entities should ref this table

### Trial table

The "ideal" trial model is built from a set of matched trial records. Each trial record is obtained from a public register.

Our first approach to building a trial model will be:

1. Choose a resolution order for registers, for where to pick fields from
2. Map fields from trial records to WHO Data Set fields
3. Store additional fields of data in the "data" field

  * Fields (at least: obviously more fields are relevant):
    * All the WHO Data Set
    * Identifiers (object with multiple unique identifiers for the trial, likely keyed by type of identifier)
    * References to the above ref. tables
    * A data field (JSONB) to hold extra data (let's see what we have when we do initial matching)
    * A discrepancies field (JSONB, or ref to table) in order to store *conflicts* in information from the registers

### TrialRecord table

An actual record of a trial.

  * Fields (at least. obviously more fields are relevant):
    * Data (probably JSONB as the structure of records are wildly inconsistent)
    * Provenance info, extraction data, etc.
    * Trial: ref to Trial object this is mapped to

### Publication table

Reports, papers, reviews on a trial.

  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
    * Source (URL) (maybe a publication has many sources...)
    * Cache (Our URL)
    * Data (JSONB, or ref to table. For example, OCR'd text of the publication). Not sure we worry about this until it is actual, but adding for reference.

### Document table

A range of documents associated with a trial. Example: patient information sheets, consent forms. 

  * Fields (at least. obviously more fields are relevant):
    * Name
    * Type (ENUM)
    * Source (URL)
    * Cache (Our URL)
    * Data (JSONB, or ref to table. For example, OCR'd text of the publication). Not sure we worry about this until it is actual, but adding for reference.

# Tasks

* [ ] Succinct document that describes the first iteration of the schema
* [ ] Implementation of schema with a sample of the data we've scraped from trial registers

**Comment by roll** [comment]
@vitorbaptista it's looks like it's ready to mark as done

**Comment by pwalsh** [comment]
DONE
