### ISSUE TITLE
First iteration database issues

### ISSUE THREAD

**Issue by roll** [opentrials/api#7]
Schema:
- [ ] add more fields based on `API/Apps` needs
- [ ] decide about `eligibility_criteria` based on `API/Apps` needs (freejson for now)
- [ ] decide about `primary/secondary_outcomes` based on `API/Apps` needs (freejson for now)
- [ ] add `organisation_person, publication_person` relationships
- [ ] iteratively decide adding/removing nullable to fields

**Comment by pwalsh** [comment]
@roll can i close this? surely it is captured elsewhere?

**Comment by roll** [comment]
@pwalsh that's original for @vitorbaptista to review and decide

**Comment by pwalsh** [comment]
@vitorbaptista WDYT?

**Comment by pwalsh** [comment]
I'm closing this, issues will arise in relation to other tasks, meeting user stories.
